In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

In [2]:
title = pd.read_csv("./netflix_titles.csv")
title.head

<bound method NDFrame.head of      show_id     type                  title         director  \
0         s1    Movie   Dick Johnson Is Dead  Kirsten Johnson
1         s2  TV Show          Blood & Water              NaN
2         s3  TV Show              Ganglands  Julien Leclercq
3         s4  TV Show  Jailbirds New Orleans              NaN
4         s5  TV Show           Kota Factory              NaN
...      ...      ...                    ...              ...
8802   s8803    Movie                 Zodiac    David Fincher
8803   s8804  TV Show            Zombie Dumb              NaN
8804   s8805    Movie             Zombieland  Ruben Fleischer
8805   s8806    Movie                   Zoom     Peter Hewitt
8806   s8807    Movie                 Zubaan      Mozez Singh

                                                   cast        country  \
0                                                   NaN  United States
1     Ama Qamata, Khosi Ngema, Gail Mabalane, Thaban...   South Africa
2     Sami Bouajila, Tracy Gotoas, Samuel Jouy, Nabi...            NaN
3                                                   NaN            NaN
4     Mayur More, Jitendra Kumar, Ranjan Raj, Alam K...          India
...                                                 ...            ...
8802  Mark Ruffalo, Jake Gyllenhaal, Robert Downey J...  United States
8803                                                NaN            NaN
8804  Jesse Eisenberg, Woody Harrelson, Emma Stone, ...  United States
8805  Tim Allen, Courteney Cox, Chevy Chase, Kate Ma...  United States
8806  Vicky Kaushal, Sarah-Jane Dias, Raaghav Chanan...          India

              date_added  release_year rating   duration  \
0     September 25, 2021          2020  PG-13     90 min
1     September 24, 2021          2021  TV-MA  2 Seasons
2     September 24, 2021          2021  TV-MA   1 Season
3     September 24, 2021          2021  TV-MA   1 Season
4     September 24, 2021          2021  TV-MA  2 Seasons
...                  ...           ...    ...        ...
8802   November 20, 2019          2007      R    158 min
8803        July 1, 2019          2018  TV-Y7  2 Seasons
8804    November 1, 2019          2009      R     88 min
8805    January 11, 2020          2006     PG     88 min
8806       March 2, 2019          2015  TV-14    111 min

                                              listed_in  \
0                                         Documentaries
1       International TV Shows, TV Dramas, TV Mysteries
2     Crime TV Shows, International TV Shows, TV Act...
3                                Docuseries, Reality TV
4     International TV Shows, Romantic TV Shows, TV ...
...                                                 ...
8802                     Cult Movies, Dramas, Thrillers
8803             Kids' TV, Korean TV Shows, TV Comedies
8804                            Comedies, Horror Movies
8805                 Children & Family Movies, Comedies
8806     Dramas, International Movies, Music & Musicals

                                            description
0     As her father nears the end of his life, filmm...
1     After crossing paths at a party, a Cape Town t...
2     To protect his family from a powerful drug lor...
3     Feuds, flirtations and toilet talk go down amo...
4     In a city of coaching centers known to train I...
...                                                 ...
8802  A political cartoonist, a crime reporter and a...
8803  While living alone in a spooky town, a young g...
8804  Looking to survive in a world taken over by zo...
8805  Dragged from civilian life, a former superhero...
8806  A scrappy but poor boy worms his way into a ty...

[8807 rows x 12 columns]>

# データ概要

In [3]:
title.shape

(8807, 12)

In [4]:
title.isnull().sum()

show_id            0
type               0
title              0
director        2634
cast             825
country          831
date_added        10
release_year       0
rating             4
duration           3
listed_in          0
description        0
dtype: int64

In [5]:
title.dtypes

show_id           str
type              str
title             str
director          str
cast              str
country           str
date_added        str
release_year    int64
rating            str
duration          str
listed_in         str
description       str
dtype: object

In [6]:
title.describe()

       release_year
count   8807.000000
mean    2014.180198
std        8.819312
min     1925.000000
25%     2013.000000
50%     2017.000000
75%     2019.000000
max     2021.000000

In [7]:
# 重複確認
title.duplicated().sum()
# 重複削除
# title = title.drop_duplicates()

np.int64(0)

# 前処理

## 日付変更

### date_added

In [8]:
title["date_added"] = pd.to_datetime(title["date_added"], errors="coerce")
title["date_added"].head()

0   2021-09-25
1   2021-09-24
2   2021-09-24
3   2021-09-24
4   2021-09-24
Name: date_added, dtype: datetime64[us]

## 欠損値処理

director：unknownで補完
cast：unknownで補完
country：unknownで補完
date_added：そのまま
rating：unknownで補完
duration：unknownで補完

In [9]:
title["director"]=title["director"].fillna("Unknown")
title["director"].head()

0    Kirsten Johnson
1            Unknown
2    Julien Leclercq
3            Unknown
4            Unknown
Name: director, dtype: str

In [10]:
title["cast"]=title["cast"].fillna("Unknown")
title["country"]=title["country"].fillna("Unknown")
title["rating"]=title["rating"].fillna("Unknown")
title["duration"]=title["duration"].fillna("Unknown")

## カラム追加

### 追加年

In [11]:
title["add_year"]=title["date_added"].dt.year
title["add_year"].head()

0    2021.0
1    2021.0
2    2021.0
3    2021.0
4    2021.0
Name: add_year, dtype: float64

### 追加月

In [12]:
title["add_month"]=title["date_added"].dt.month
title["add_month"]

0        9.0
1        9.0
2        9.0
3        9.0
4        9.0
        ...
8802    11.0
8803     7.0
8804    11.0
8805     1.0
8806     3.0
Name: add_month, Length: 8807, dtype: float64

# 最終確認

In [13]:
title.shape

(8807, 14)

In [17]:
title.to_csv("./netflix_processing.csv")

In [23]:
title.columns

Index(['show_id', 'type', 'title', 'director', 'cast', 'country', 'date_added',
       'release_year', 'rating', 'duration', 'listed_in', 'description',
       'add_year', 'add_month'],
      dtype='str')

In [38]:
title[title["rating"]=="74 min"]

,show_id,type,title,director,cast,country,date_added,release_year,rating,duration,listed_in,description,add_year,add_month
5541,s5542,Movie,Louis C.K. 2017,Louis C.K.,Louis C.K.,United States,2017-04-04,2017,74 min,Unknown,Movies,"Louis C.K. muses on religion, eternal love, gi...",2017.0,4.0